version: '2'
services:
    elasticsearch1:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
        container_name: elasticsearch1
        environment:
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        mem_limit: 1g
        volumes:
          - ./data/elasticsearch:/usr/share/elasticsearch/data
        ports:
          - 9200:9200

    etreedb:
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ../api.etreedb.org:/var/www/html/api.etreedb.org
            - ../utf8convert.etreedb.org:/var/www/html/utf8convert.etreedb.org
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
           context: .
           dockerfile: build/php-fpm
        links:
            - mysql
            - elasticsearch1
        ports:
            - "9000:9000"
        volumes:
            - ../api.etreedb.org:/var/www/html/api.etreedb.org
            - ../utf8convert.etreedb.org:/var/www/html/utf8convert.etreedb.org
            - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=123
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./config/my.cnf:/etc/mysql/conf.d/custom.cnf
